[gcp_service_account]
type = "service_account"
project_id = "keskia-453517"
private_key_id = "10ea57b36dbdc13a8341e5aa057452cdc63e496e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCUXAl1TtnqB4Lo
RhfzQdu1e4VtifxR18tkB3cSFFOHzSecgBOt75q90ndr8Rcky6wM6P7eWO+l4SUD
u+UciPxx4J0ndwZu5TPKqLVBXFcpXjx5QrzRJ+ecKac6yxsMLIKPNgLuWMycMg98
m72U1DxquvKlggqZOxav+IlHWsWPXWhMRvc/TPghnoQsbZVWleHmD9xaX8tXV01W
xVKUnbxK1iV+NygOQDTCfvIanBcasODKtR/geS+DEHr6UWmrlEbQoamShhJupO9S
QAQW+b00O1SZPHCm9Wp9jyh20Ax8m1GM9G2BsB5x/f5kua2YAenPtesPDQJM1ehz
OxmoMCrTAgMBAAECggEANZSr4c8RiqEd2S9/dN5jMD8lKDN+ijxqe3zqtv/aTyB7
3tyuvtHbTBUYBkbzOdnJEHyRl9H88ybGDHwuuciLi8E4YMlu7FwhAV8+3xUvcYRU
SOMeeFd2IYM1n1k9Mn9cw8YY9uXhN8QorbM9m+Ou0kkkWzwFAeRCRFl5kuiokyb3
GGzrA2nOCT2K2axEwwod/PMnq17GGLqhc80YO2y8ATFC7YVsy5VBBR3ahlVvQR1f
NqdvO7U8YnDLAw1ussf57UlDmgpMW7MU8YZZyYh5387jG8yNZu9Cmx5xdh8IZede
gmtnDWI/2AOblUnLZ2uDbXSTEW2LBz3IgJFi67TEWQKBgQDMQh80pA5/Y3U+eLvH
nIc4y08CnekFb/whKBpy6Na3Vp+sq4To3uGJPxXCiuJDhNORpjR2Qhi3aUrFM7U9
voWoaFcelstWzAGu/3m7TOghfBGbFmFjUnLLMGSCvvKjm5ylkfk680YdPiO6mfAv
GGz3zCJ9pJVQomo0NqDM70LqVQKBgQC58PRLL2mAxIaGghH5K7CSxOKGO3VtRfnc
TXyXp0+TUBGcPIaBEG+cozX3Q1LBjKoMor+yz4ISrFt+YPgFuN/M2QXG69/exqZQ
5b9seNbJkIwS7da5O1LlnzREZCfhxKYmiXLId1GqpsFRKWDX697wKjA6zv5/ZWKh
4OK6YhQ4hwKBgFeFCXvzw6Z/xi/jaYppHmOOcadMZBkJV74ZQeP0snPSMQ66W3Ow
dHDrT/aQrcyCcGjbD2WQgqir+/atZj4zkW+Mba/UqwHg3ePO4akIlforABw0pbv6
CufXL2n6SVsjBSbIekLxFBzZkFOXPBvh2mb+19SAHd50CQ+gTJwi9MgVAoGADujS
PeEcXZXkj46IcGlfbDVbUJYd8VgmE9MmxWZGDDLkZpm300uFF5NCtYPxc9GapQ67
vlPDQ0oMwBJ4cMUFNQDF5NBvEAbvuRbjBYie+GSdxrrJd+rY186vOziotgK1q+tj
h82Bf+SFJcPinw2rv6gyW9TTNVXk1cQZigZpRqsCgYEAysSK/Wg8LhxgvKgZ23F8
5aMcr8KqAa25LhOwCU6YRnVVxTb/+Xcnei51rl+d/tfMKlN2DjsvU0labEwhL0WC
qfFb1QRBxUSbxL2vELmbQ0E5bLWmudAhCYB1x6TlESEMjqdX0jqFn/K5GPPT0+YD
VN3Iqn+aMUzDUGxF2M6cKFU=
-----END PRIVATE KEY-----"""
client_email = "parcoursursa@keskia-453517.iam.gserviceaccount.com"
client_id = "108626103262688077831"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/parcoursursa%40keskia-453517.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[azure]
AZURE_API_KEY = "70vwwlq5J8a2CrqnMZVfxY83ztdx6Ahgor5y2WbUHtTBgOhuROIdJQQJ99BDAC5T7U2XJ3w3AAABACOGrF5i"
AZURE_ENDPOINT = "https://oai-test-rg-test.openai.azure.com/"
AZURE_DEPLOYMENT = "gpt-4o"
AZURE_API_VERSION = "2025-01-01-preview"